# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 209f5d76fadf7f331b7cfd4430ab61435284bab59ac37fafaddbd920968937fa70fceced057876caa038eb595a4ce3017d3c8a50cad288b8d56d23099f947b6f
  super_secret_key: AIzaSyDGvgS-p6cR5loLAz3OVlo6sutDlQ8Bz1A

test:
  secret_key_base: 08f9af3247f53d28f3caf9713c3f994a49f11cf5d4d9d16d1a90509090ee4f555715a5404625affee7c0f9c693d7b56542d74ec215519a7df85fe1601c53c900
  super_secret_key: AIzaSyDGvgS-p6cR5loLAz3OVlo6sutDlQ8Bz1A

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  super_secret_key: <%= ENV["SUPER_SECRET_KEY"] %>
